config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
     :sessions => 'admins/sessions'
  }
 
    devise_scope :admin do
     get "dashboard", :to => "dashboard#index"
     get "dashboard/login", :to => "admins/sessions#new"
     post "dashboard/login", :to => "admins/sessions#create"
     delete "dashboard/logout", :to => "admins/sessions#destroy"
    end
    
    namespace :dashboard do
     resources :users, only: [:index, :destroy]
     resources :major_categories, except: [:new]
     resources :categories, except: [:new]
     resources :products, except: [:show] do
       collection do
         get  "import/csv", :to => "products#import"
         post "import/csv", :to => "products#import_csv"
         get  "import/csv_download", :to => "products#download_csv"
       end
     end
     resources :orders, only: [:index]
    end


  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "verify", :to => "users/registrations#verify"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
      get    "cart",               :to => "shopping_carts#index"
      delete "cart",               :to => "shopping_carts#destroy"
      post   "cart/create",        :to => "shopping_carts#create"
      get    "mypage",                 :to => "users#mypage"
      put    "mypage",                 :to => "users#update"
      get    "mypage/edit",            :to => "users#edit"
      get    "mypage/edit_password",   :to => "users#edit_password"
      delete "mypage/delete",          :to => "users#destroy"
      get    "mypage/address/edit",    :to => "users#edit_address"
      put    "mypage/password",        :to => "users#update_password"
      get    "mypage/favorite",        :to => "users#favorite"
      get    "mypage/cart_history",    :to => "users#cart_history_index", :as => "mypage_cart_histories"      
      get    "mypage/cart_history/:num", :to => "users#cart_history_show", :as => "mypage_cart_history"
      get    "mypage/register_card",     :to => "users#register_card"
      post   "mypage/token",             :to => "users#token"    
    end
  end
  
  resources :products do
    member do
      get :favorite
    end
    resources :reviews, only: [:create]
  end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: :index
  before_action :set_category, only: %w[show edit update destroy]
  layout "dashboard/dashboard"

  def index
    @categories = Category.display_list(params[:page])
    @category = Category.new
    @major_categories = MajorCategory.all
  end

  def show
  end

  def create
    category = Category.new(category_params)
    category.save
    redirect_to dashboard_categories_path
  end

  def edit
    @major_categories = MajorCategory.all
  end

  def update
    major_category_id = category_params[:major_category_id]
    major_category = MajorCategory.find(major_category_id)

    wk_category_params = category_params
    wk_category_params[:major_category_name] = major_category.name

    @category.update(wk_category_params)
    @category.save
    redirect_to dashboard_categories_path
  end

  def destroy
    @category.destroy
    redirect_to dashboard_categories_path
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name,:description,:major_category_name)
    end
end

app/controllers/dashboard/major_categories_controller.rb
class Dashboard::MajorCategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_major_category, only: %w[show edit update destroy]
  layout "dashboard/dashboard"

  def index
    @major_categories = MajorCategory.display_list(params[:pages])
    @major_category = MajorCategory.new
  end

  def show
  end

  def create
    major_category = MajorCategory.new(major_category_params)
    major_category.save
    redirect_to dashboard_major_categories_path
  end

  def edit
  end

  def update
    @major_category.update(major_category_params)
    redirect_to dashboard_major_categories_path
  end

  def destroy
    @major_category.destroy
    redirect_to dashboard_major_categories_path
  end

  private
    def major_category_params
      params.require(:major_category).permit(:name, :description)
    end

    def set_major_category
        @major_category = MajorCategory.find(params[:id])        
    end
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < ApplicationController
  before_action :authenticate_admin!
  layout "dashboard/dashboard"

  def index
    if params[:code].present?
        @orders = ShoppingCart.search_bought_carts_by_ids(params[:code]).page(params[:page]).per(15)
    else
        @orders = ShoppingCart.bought_carts.page(params[:page]).per(15)
    end   
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %w[show edit update destroy]
  layout "dashboard/dashboard"

  def index
    @sorted = ""
    @sort_list = Product.sort_list

    if params[:sort].present?
      @sorted = params[:sort]
    end

    if params[:keyword].present?
      keyword = params[:keyword].strip
      @total_count = Product.search_for_id_and_name(keyword).count
      @products = Product.search_for_id_and_name(keyword).display_list(params[:pages])
    else
      @total_count = Product.count
      @products = Product.sort_order(@sorted).display_list(params[:page])
    end
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to dashboard_products_path
  end

  def edit
    @categories = Category.all
  end

  def update
    @product.update(product_params)
    redirect_to dashboard_products_path
  end

  def destroy
    @product.destroy
    redirect_to dashboard_products_path
  end
  
  def import
  end
 
  def import_csv
     if params[:file] && File.extname(params[:file].original_filename) == ".csv"
       Product.import_csv(params[:file])
       flash[:success] = "CSVでの一括登録が成功しました!"
       redirect_to import_csv_dashboard_products_url
     else
       flash[:danger] = "CSVが追加されていません。CSVを追加してください。"
       redirect_to import_csv_dashboard_products_url
     end
  end
 
  def download_csv
     send_file(
       "#{Rails.root}/public/csv/products.csv",
       filename: "products.csv",
       type: :csv
     )
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
       params.require(:product).permit(:name, :description, :price, :recommended_flag, :carriage_flag, :category_id, :image)
    end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :authenticate_admin!
  layout "dashboard/dashboard"

 def index
   if params[:keyword].present?
       @keyword = params[:keyword].strip
       @users = User.search_information(@keyword).display_list(params[:pages])
   else
       @keyword = ""
       @users = User.display_list(params[:pages])
   end
 end
 
 def destroy
     user = User.find(params[:id])
     deleted_flg = User.switch_flg(user.deleted_flg)
     user.update(deleted_flg: deleted_flg)
     redirect_to dashboard_users_path
 end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_admin!
    layout 'dashboard/dashboard'
    
    def index 
     @sort = params[:sort]
     @sort_list = ShoppingCart.sort_list 
     
     if @sort == "month"
       sales = ShoppingCart.get_monthly_sales
     else
       sales = ShoppingCart.get_daily_sales
     end
     
     @sales = Kaminari.paginate_array(sales).page(params[:page]).per(15)
    end

end

app/helpers/dashboard/categories_helper.rb
module Dashboard::CategoriesHelper
end

app/helpers/dashboard/major_categories_helper.rb
module Dashboard::MajorCategoriesHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/dashboard/products_helper.rb
module Dashboard::ProductsHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/layouts/dashboard/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light shadow-sm samuraimart-header-container">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "/images/logo.jpg" %>
  <% end %>
</nav>

app/views/layouts/dashboard/_sidebar.html.erb
<div class="container ml-3">
  <h2>受注管理</h2>
  <div class="d-flex flex-column">
     <label class="techmart-sidebar-category-label">
       <%= link_to "受注一覧", dashboard_orders_path %>
     </label>  
  </div>

  <h2>商品管理</h2>
  <div class="d-flex flex-column">
    <label class="techmart-sidebar-category-label">
       <%= link_to "商品一覧", dashboard_products_path %>
     </label>
    <label class="techmart-sidebar-category-label">
       <%= link_to "親カテゴリ管理", dashboard_major_categories_path %>
     </label>
    <label class="techmart-sidebar-category-label">
      <%= link_to "カテゴリ管理", dashboard_categories_path %>
    </label>
    <label class="techmart-sidebar-category-label">
       <%= link_to "CSV一括登録", import_csv_dashboard_products_path %>
     </label>
  </div>

  <h2>顧客管理</h2>
  <div class="d-flex flex-column">
    <label class="techmart-sidebar-category-label">
       <%= link_to "顧客一覧", dashboard_users_path %>
    </label>
  </div>

  <h2>その他</h2>
  <div class="d-flex flex-column">
    <label class="techmart-sidebar-category-label">新着情報管理</label>
    <label class="techmart-sidebar-category-label">管理ユーザー管理</label>
  </div>
</div>

app/views/layouts/dashboard/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV["APP_NAME"] %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/8aeca36c69.js" crossorigin="anonymous"></script>
  </head>

  <body>
      <%= render partial: 'layouts/dashboard/header' %>
    <div class="row">
        <div class="col-3 mt-3">
         <%= render partial: 'layouts/dashboard/sidebar' %>
       </div>
      <div class="col">
        <main class="py-4 mb-5">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>